### ISSUE TITLE
"Status: Room is Locked" 

### ISSUE THREAD

**Issue by MRYingLEE** [Temasys/getaroom#10]
I cloned getaroom.io at http://Click2.Biz.

I didn't change any code. I only changed the 2 API keys and host name. But I always met the problem of "Status: Room is Locked" once I opened the website.

I tried to use 1 app key and 1 its alias key and also I tried 2 API keys in the mentioned configs.jsx file. But I always met the same problem.

At the end I will try to connect an Android APP with the web site. 

Please help. 

Thank you in advance,

Ying

**Comment by MRYingLEE** [comment]
Let me add more more.

When I tried https://click2.biz/ (HTTPS instead of HTTP). The homepage is nearly blank.

Please help.

Thank you in advance,

Ying

**Comment by patelniral** [comment]
I am facing same problem.How can I solved it?
Please help.

Thank you,

**Comment by letchoo** [comment]
This relates to other underlying issues more than room being locked - when the Application key is invalid etc. Will look into it and update the statuses with more details if possible
