### ISSUE TITLE
Cannot join a room when user's audio device is disabled.

### ISSUE THREAD

**Issue by srikinfin** [Temasys/getaroom#11]
**Expected** : Even when the audio device is disabled, If the video device(webcam) is enabled, User should be able to see the video feed.

**Present** : When the Audio device is disabled, Even thought the webcam is working, User is not able to join a session.

**Environment** : Windows 10 as a Standard user where microphone/Input device is disabled.
                       Google chrome, Version 46.0.2490.86 m

Error in console shown below

`SkylinkJS - <<MediaStream>> Failed retrieving stream: Error: Expected audio tracks length with 1 and video tracks length with 1 but received audio tracks length with 0 and video tracks length with 1
    at https://cdn.temasys.com.sg/skylink/skylinkjs/0.6.x/skylink.debug.js:13273:38_logFn @ skylink.debug.js:7878
skylink.debug.js:7880 SkylinkJS - <<Event>> (mediaAccessError) Condition is met. Firing event`

**Comment by letchoo** [comment]
This relates to a SkylinkJS issue that is resolved in 0.6.6 https://github.com/Temasys/SkylinkJS/issues/163
