### ISSUE TITLE
not work in Firefox 43+?

### ISSUE THREAD

**Issue by DetritusA** [Temasys/getaroom#15]
https://getaroom.io/

trying to connect firefox (43.0.1) with chrome (49.0.2623.110)
an error occurred "ICE failed, see about:webrtc for more details"

log cut:

SkylinkJS [ovq_Vzb6C-zhgmItAADE] - Adding local stream
skylink.debug.js (line 7992)
SkylinkJS [ovq_Vzb6C-zhgmItAADE] - <<MediaStream>> Sending stream LocalMediaStream { endedInterval=126,  recordedTime=31.98548752834467,  id="{433762ae-5923-406d-812d-68421ee41095}",  more...}
skylink.debug.js (line 7990)
SkylinkJS [ovq_Vzb6C-zhgmItAADE] - Sending restart message to signaling server
skylink.debug.js (line 7992)
SkylinkJS [ovq_Vzb6C-zhgmItAADE] - Sending to peer -> Object { type="restart",  mid="uTAWMCBKXNrvh-DVAADD",  rid="3db97d5114b01cbf7e561fca...0bd48c05380c_api_1c54c3",  more...}
skylink.debug.js (line 7990)
SkylinkJS - <<Event>> (peerRestart) Event is triggered
skylink.debug.js (line 7992)
SkylinkJS [ovq_Vzb6C-zhgmItAADE] - <<PeerConnectionHealth>> Initializing check for peer's connection health
skylink.debug.js (line 7992)
**ICE failed, see about:webrtc for more details**
SkylinkJS - <<Socket>> Received message
skylink.debug.js (line 7992)
SkylinkJS - <<Event>> (channelMessage) Event is triggered
skylink.debug.js (line 7992)
SkylinkJS [ovq_Vzb6C-zhgmItAADE] - Received from peer -> offer
skylink.debug.js (line 7990)
SkylinkJS [ovq_Vzb6C-zhgmItAADE] - (offer) Received offer from peer. Session description:

v=0

**Comment by letchoo** [comment]
Hi @DetritusA, are you able to get video/audio connection later?

**Comment by DetritusA** [comment]
this issue is not actual
all works fine in FF 46.0
