### ISSUE TITLE
Deploying via S3

### ISSUE THREAD

**Issue by waltermvp** [Temasys/getaroom#25]
First and foremost great example, thank you. 

I have deployed a staging version of the react site to a S3 bucket, and it seems to be working fine with the exception of getting the video and audio started. The deployed instance (on S3) is able to connect to a room successfully, however I never get the video/audio permission request and the following UI.  

<img width="806" alt="screen shot 2018-02-05 at 12 22 19 pm" src="https://user-images.githubusercontent.com/1158238/35818915-459e854c-0a6f-11e8-98d3-9e8d75a1d59c.png">

Can this be because I don't have SSL fully configured?

**Comment by alsmyr** [comment]
You need to serve the client over https in order to get the streams

**Comment by waltermvp** [comment]
thank you very much. I'll add SSL and test
